import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { BrowserRouter, Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import './App.css'

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api'
type User = { id: string; full_name: string; email: string; company_id: string; role: string }
type Session = { access_token: string; user: User }
type Agent = { id: string; device_name: string; platform: string; version: string; status: string; last_seen_at: string | null; mailbox_email: string | null; mailbox_connected: boolean }
type OverviewData = { user: User; agents: Agent[]; metrics: { email_count: number; reschedule_count: number; online_agents: number }; google_connected: boolean }
type Message = { id: string; sender: string | null; subject: string | null; body_preview: string | null; received_at: string | null; classification: string; processed: boolean }

async function api<T>(path: string, session: Session, options: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...options, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json', ...(options.headers ?? {}) } })
  const data = await response.json()
  if (!response.ok) throw new Error(data.detail ?? 'Request failed')
  return data
}

function App() { return <BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route path="/" element={<Navigate to="/dashboard" replace />} /><Route path="/dashboard" element={<Protected />}><Route index element={<OverviewPage />} /><Route path="rescheduling" element={<ReschedulingPage />} /><Route path="approvals" element={<ApprovalsPage />} /><Route path="ranking" element={<RankingPage />} /><Route path="integrations" element={<IntegrationsPage />} /><Route path="audit" element={<AuditPage />} /><Route path="notifications" element={<NotificationsPage />} /><Route path="settings" element={<SettingsPage />} /></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></BrowserRouter> }

function Login() { const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? 'Unable to login'); localStorage.setItem('recruiter-session', JSON.stringify(data)); navigate('/dashboard') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to login') } }; return <main className="login-page"><div className="login-art"><div className="brand-large"><b>IK</b><span>IKRGY Recruiting Automation</span></div><p>Controlled recruiting operations, connected to the work already happening in your inbox and calendar.</p></div><form className="login-form" onSubmit={submit}><span className="eyebrow">Secure workspace</span><h1>Welcome back.</h1><p>Sign in with your registered recruiter or admin account.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary wide">Sign in <span>→</span></button><small>Access is provisioned by your organization. There is no public registration.</small></form></main> }

function Protected() { const saved = localStorage.getItem('recruiter-session'); if (!saved) return <Navigate to="/login" replace />; return <Portal session={JSON.parse(saved)} /> }
function Portal({ session }: { session: Session }) { const navigate = useNavigate(); const location = useLocation(); const [data, setData] = useState<OverviewData | null>(null); const [error, setError] = useState(''); useEffect(() => { api<OverviewData>('/portal/overview', session).then(setData).catch(e => setError(e.message)) }, [session]); const logout = () => { localStorage.removeItem('recruiter-session'); navigate('/login') }; const nav = [['/dashboard', 'Overview', '◫'], ['/dashboard/rescheduling', 'Rescheduling Agent', '↻'], ['/dashboard/approvals', 'Approval Queue', '✓'], ['/dashboard/ranking', 'Ranking & Alerts', '★'], ['/dashboard/integrations', 'Integrations', '⛓'], ['/dashboard/audit', 'Audit & Observability', '◎'], ['/dashboard/notifications', 'Notifications', '◉'], ['/dashboard/settings', 'Admin Settings', '⚙']] as const; return <div className="app-shell"><aside className="sidebar"><Link className="brand" to="/dashboard"><strong>IK</strong><span><b>IKRGY</b>Recruiting Automation</span></Link><div className="env-chip">database mode · live</div><nav>{nav.map(([path, label, icon]) => <Link className={`nav-link ${location.pathname === path ? 'active' : ''}`} to={path} key={path}><i>{icon}</i>{label}</Link>)}</nav><div className="sidebar-foot"><div className="security-note"><b>Recruiter-controlled</b><span>No automatic hiring decisions.</span></div><button className="ghost full" onClick={logout}>Sign out</button></div></aside><main className="main"><header className="topbar"><div><h1>{titleFor(location.pathname)}</h1><p>Live operating view for the recruiting automation platform</p></div><div className="top-actions"><span className="live-dot" /> {data?.user.full_name ?? 'Loading'} <span className="role-pill">{data?.user.role ?? 'user'}</span></div></header><section className="content">{error && <div className="error banner">{error}</div>}<Outlet context={{ session, data, refresh: () => api<OverviewData>('/portal/overview', session).then(setData) }} /></section></main></div> }
function titleFor(path: string) { const value = path.split('/').pop(); return ({ dashboard: 'Recruiting Operations', rescheduling: 'Workflow 1 · Candidate Rescheduling Agent', approvals: 'Approval Queue', ranking: 'Workflow 2 · Candidate Ranking & Recruiter Alert', integrations: 'Integrations', audit: 'Audit & Observability', notifications: 'Notifications', settings: 'Admin Settings' } as Record<string, string>)[value ?? 'dashboard'] }
function OverviewPage() { const { data } = useOutletData(); if (!data) return <Loading />; return <><section className="hero-strip"><div><span className="eyebrow">Shared platform spine</span><h2>Two workflows. One controlled recruiting platform.</h2><p>Live data from your registered users, connected systems, and synced mailbox.</p></div><div className="hero-actions"><Link className="primary" to="/dashboard/rescheduling">Open rescheduling</Link><Link className="secondary" to="/dashboard/ranking">Open ranking</Link></div></section><div className="kpi-grid"><Kpi label="Synced emails" value={data.metrics.email_count} tone="cyan" /><Kpi label="Reschedule requests" value={data.metrics.reschedule_count} tone="violet" /><Kpi label="Online agents" value={data.metrics.online_agents} tone="green" /><Kpi label="Connected Google" value={data.google_connected ? 'Yes' : 'No'} tone="orange" /></div><div className="grid-2"><Panel title="Workflow health" subtitle="Runtime stages and control gates"><div className="workflow"><Workflow label="Inbox → calendar → approval → reply" /><Workflow label="Recruiter review remains final" alt /></div></Panel><Panel title="Connected systems" subtitle="Database-backed agent status"><div className="list">{data.agents.slice(0, 5).map(agent => <div className="list-row" key={agent.id}><span className={`status-dot ${agent.status}`} /><div><b>{agent.device_name}</b><small>{agent.mailbox_email ? `Mailbox: ${agent.mailbox_email}` : 'Mailbox selection required'}</small></div><span className="badge">{agent.status}</span></div>)}{!data.agents.length && <Empty text="No agents registered yet." />}</div></Panel></div></> }
function ReschedulingPage() { const { session } = useOutletData(); const [messages, setMessages] = useState<Message[]>([]); const [status, setStatus] = useState(''); useEffect(() => { api<Message[]>('/integrations/google/gmail/messages', session).then(setMessages).catch(e => setStatus(e.message)) }, [session]); return <><PageIntro kicker="Workflow 1" title="Candidate rescheduling." copy="Gmail messages are classified from live synced data. Calendar changes remain approval-controlled." /><Panel title="Inbox signals" subtitle="Reschedule requests from the database"><div className="table-wrap"><table><thead><tr><th>Sender</th><th>Subject</th><th>Received</th><th>Classification</th></tr></thead><tbody>{messages.map(message => <tr key={message.id}><td>{message.sender}</td><td>{message.subject}</td><td>{message.received_at ?? '—'}</td><td><span className="badge">{message.classification}</span></td></tr>)}</tbody></table>{!messages.length && <Empty text={status || 'No synced messages. Connect Google and run Gmail sync.'} />}</div></Panel></> }
function ApprovalsPage() { return <><PageIntro kicker="Human-in-the-loop" title="Approval queue." copy="Only backend-created workflow proposals appear here. No sample approvals are shown." /><Panel title="Pending review" subtitle="Live automation records"><Empty text="No pending approvals in the database." /></Panel></> }
function RankingPage() { return <><PageIntro kicker="Workflow 2" title="Ranking and recruiter alerts." copy="Candidate rankings will appear here once requisition and applicant APIs are connected." /><Panel title="Active requisitions" subtitle="Database-backed records only"><Empty text="No requisitions available from the backend yet." /></Panel></> }
function IntegrationsPage() { const { session, data } = useOutletData(); return <><PageIntro kicker="Adapter boundary" title="Integrations." copy="Connect Google to enable Gmail reading, Calendar availability, and controlled replies." /><div className="integration-grid"><Integration name="Gmail / Google Workspace" status={data?.google_connected ? 'connected' : 'not connected'} action={async () => { const result = await api<{ authorization_url: string }>('/integrations/google/authorize', session); window.location.href = result.authorization_url }} /><Integration name="Google Calendar" status={data?.google_connected ? 'connected' : 'not connected'} action={async () => { const result = await api<{ authorization_url: string }>('/integrations/google/authorize', session); window.location.href = result.authorization_url }} /></div></> }
function AuditPage() { return <><PageIntro kicker="Observability" title="Audit trail." copy="Every workflow action will be rendered from backend audit records as that API is added." /><Panel title="Append-only event trail" subtitle="Trigger, decisions, guardrails, approvals, actions"><Empty text="No audit events available from the backend." /></Panel></> }
function NotificationsPage() { return <><PageIntro kicker="Operations" title="Notifications." copy="Recruiter-facing updates will appear here from backend workflow events." /><Panel title="All channels" subtitle="Email · Dashboard"><Empty text="No notifications available." /></Panel></> }
function SettingsPage() { const { data } = useOutletData(); return <><PageIntro kicker="Configuration" title="Admin settings." copy="Settings are shown from live backend state. Policy mutations remain backend-controlled." /><Panel title="Workspace access" subtitle="Current authenticated account"><div className="settings"><div><span>Role</span><b>{data?.user.role ?? '—'}</b></div><div><span>Company</span><b>{data?.user.company_id ?? '—'}</b></div><div><span>Google connection</span><b>{data?.google_connected ? 'Connected' : 'Not connected'}</b></div></div></Panel></> }
function PageIntro({ kicker, title, copy }: { kicker: string; title: string; copy: string }) { return <div className="page-intro"><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{copy}</p></div> }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="card"><div className="card-head"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</section> }
function Kpi({ label, value, tone }: { label: string; value: string | number; tone: string }) { return <div className={`kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>From live database</small></div> }
function Workflow({ label, alt = false }: { label: string; alt?: boolean }) { return <div className="workflow-row"><span className={`workflow-mark ${alt ? 'alt' : ''}`}>✓</span><div><b>{label}</b><small>{alt ? 'Human decision boundary' : 'Backend automation path'}</small></div></div> }
function Integration({ name, status, action }: { name: string; status: string; action: () => void }) { return <section className="integration-card"><div className="integration-title"><span className="integration-logo">{name[0]}</span><div><h3>{name}</h3><p>OAuth 2.0 API</p></div></div><span className="badge">{status}</span><button className="secondary" onClick={action}>{status === 'connected' ? 'Reconnect' : 'Connect Google'}</button></section> }
function Empty({ text }: { text: string }) { return <div className="empty"><span>◌</span>{text}</div> }
function Loading() { return <div className="loading">Loading live data…</div> }
function useOutletData() { const saved = localStorage.getItem('recruiter-session'); const session = (saved ? JSON.parse(saved) : null) as Session; const [data, setData] = useState<OverviewData | null>(null); useEffect(() => { if (session) api<OverviewData>('/portal/overview', session).then(setData).catch(() => setData(null)) }, [session]); return { session, data } }
export default App
