import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { BrowserRouter, Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import './App.css'
import logo from './assets/logo.jpeg'

const API = (import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api').replace(/\/$/, '')
type User = { id: string; full_name: string; email: string; company_id: string; role: string }
type Session = { access_token: string; user: User }
type OverviewData = { user: User; metrics: { email_count: number; reschedule_count: number }; google_connected: boolean }
type Message = { id: string; sender: string | null; subject: string | null; body_preview: string | null; received_at: string | null; classification: string; processed: boolean }
type GmailStatus = { connected: boolean; email: string | null; message_count: number }
type GmailSyncResponse = { synced: number; new: number; existing: number; messages: Array<{ id: string; classification: string }> }

async function api<T>(path: string, session: Session, options: RequestInit = {}): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...options, headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json', ...(options.headers ?? {}) } })
  const data = await readResponse<T & { detail?: string }>(response)
  if (!response.ok) throw new Error(data.detail ?? 'Request failed')
  return data
}

async function readResponse<T>(response: Response): Promise<T> {
  const text = await response.text()
  const contentType = response.headers.get('content-type') ?? ''

  if (!text) {
    throw new Error(`The backend returned an empty response (${response.status} ${response.statusText}) from ${response.url}. Check that the API is running and the VITE_API_URL matches http://localhost:8000/api.`)
  }

  if (!contentType.includes('application/json')) {
    throw new Error(`The backend responded with HTML instead of JSON (${response.status} ${response.statusText}) from ${response.url}. Check the backend URL or API server: ${API}`)
  }

  try {
    return JSON.parse(text) as T
  } catch {
    throw new Error(`The backend returned invalid JSON (${response.status} ${response.statusText}) from ${response.url}. Check the backend URL or API server: ${API}`)
  }
}

function App() { useEffect(() => { document.title = 'IKRGY Recruiting Automation'; let icon = document.querySelector<HTMLLinkElement>('link[rel="icon"]'); if (!icon) { icon = document.createElement('link'); icon.rel = 'icon'; document.head.appendChild(icon) } icon.href = logo }, []); return <BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/privacy-policy" element={<PrivacyPolicy />} /><Route path="/terms-of-service" element={<TermsOfService />} /><Route path="/" element={<LandingPage />} /><Route path="/dashboard" element={<Protected />}><Route index element={<OverviewPage />} /><Route path="rescheduling" element={<ReschedulingPage />} /><Route path="approvals" element={<ApprovalsPage />} /><Route path="ranking" element={<RankingPage />} /><Route path="integrations" element={<IntegrationsPage />} /><Route path="audit" element={<AuditPage />} /><Route path="notifications" element={<NotificationsPage />} /><Route path="settings" element={<SettingsPage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter> }

function LandingPage() { return <main className="landing-page"><header className="landing-nav"><Link className="landing-brand" to="/"><img src={logo} alt="IKRGY logo" /><span>IKRGY<br /><b>Recruiting Automation</b></span></Link><nav><Link to="/privacy-policy">Privacy</Link><Link to="/terms-of-service">Terms</Link><Link className="landing-login" to="/login">Sign in <span>↗</span></Link></nav></header><section className="landing-hero"><div className="landing-copy"><span className="eyebrow">The operating layer for modern recruiting</span><h1>Move candidates forward, <em>with control.</em></h1><p>IKRGY connects inbox signals, calendars, recruiter approvals, and communication tools in one clear workspace.</p><div className="landing-actions"><Link className="primary" to="/login">Enter workspace <span>→</span></Link><Link className="landing-text-link" to="/register">Create an account <span>↗</span></Link></div></div><div className="landing-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="landing-card"><img src={logo} alt="IKRGY" /><span>RECRUITING OPERATIONS</span><strong>Inbox to outcome.</strong><small>Human review stays in the loop.</small></div></div></section><section className="landing-features"><div className="feature-intro"><span className="eyebrow">One workspace</span><h2>Clarity for every handoff.</h2><p>Keep the system connected while keeping decisions with your recruiting team.</p></div><div className="feature-list"><Feature number="01" title="Connected signals" copy="Bring Gmail, Google Calendar, Outlook, and scheduling context together." /><Feature number="02" title="Approval-first workflows" copy="Review proposed actions before important candidate communication moves." /><Feature number="03" title="Recruiter-owned outcomes" copy="Automation assists the work. Your team remains the final decision-maker." /></div></section><footer className="landing-footer"><span>© 2026 IKRGY Recruiting Automation</span><LegalLinks /></footer></main> }

function Feature({ number, title, copy }: { number: string; title: string; copy: string }) { return <article className="feature"><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article> }

function Login() { const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const data = await readResponse<Session & { detail?: string }>(response); if (!response.ok) throw new Error(data.detail ?? 'Unable to login'); localStorage.setItem('recruiter-session', JSON.stringify(data)); navigate('/dashboard') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to login') } }; return <main className="login-page"><form className="login-form" onSubmit={submit}><Link className="login-brand" to="/"><img src={logo} alt="IKRGY logo" /><span>IKRGY<br /><b>Recruiting Automation</b></span></Link><h1>Welcome back.</h1><p>Sign in to continue to your recruiting operations workspace.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary wide">Sign in <span>→</span></button><small>New to the workspace? <Link to="/register">Create an account</Link></small><LegalLinks /></form></main> }

function Register() { const navigate = useNavigate(); const [form, setForm] = useState({ full_name: '', company_email: '', password: '', confirm_password: '' }); const [error, setError] = useState(''); const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value })); const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await readResponse<Session & { detail?: string }>(response); if (!response.ok) throw new Error(data.detail ?? 'Unable to create account'); localStorage.setItem('recruiter-session', JSON.stringify(data)); navigate('/dashboard') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create account') } }; return <main className="login-page"><form className="login-form" onSubmit={submit}><Link className="login-brand" to="/"><img src={logo} alt="IKRGY logo" /><span>IKRGY<br /><b>Recruiting Automation</b></span></Link><h1>Create your account.</h1><p>Set up your recruiter workspace in a few simple steps.</p><label>Full name<input value={form.full_name} onChange={e => update('full_name', e.target.value)} required /></label><label>Work email<input type="email" value={form.company_email} onChange={e => update('company_email', e.target.value)} required /></label><label>Password<input type="password" value={form.password} onChange={e => update('password', e.target.value)} minLength={8} required /></label><label>Confirm password<input type="password" value={form.confirm_password} onChange={e => update('confirm_password', e.target.value)} minLength={8} required /></label>{error && <div className="error">{error}</div>}<button className="primary wide">Create account <span>→</span></button><small>Already registered? <Link to="/login">Sign in</Link></small><LegalLinks /></form></main> }

function LegalLinks() { return <div className="legal-links"><Link to="/privacy-policy">Privacy Policy</Link><span>·</span><Link to="/terms-of-service">Terms of Service</Link></div> }

function PrivacyPolicy() { return <LegalPage title="Privacy Policy"><h2>1. Overview</h2><p>This Privacy Policy explains how IKRGY Recruiting Automation collects, uses, stores, and protects information when you use the application.</p><h2>2. Information we collect</h2><p>We collect account details such as your name, work email, company information, and encrypted authentication data. When you connect a provider, we process the permissions and information needed to provide the requested Gmail, Google Calendar, Microsoft Outlook, email, and scheduling features.</p><h2>3. How we use information</h2><p>We use information to authenticate users, operate recruiting workflows, synchronize connected services, support calendar scheduling, communicate workflow results, maintain security, and improve reliability.</p><h2>4. Connected providers</h2><p>Provider access is initiated by you through the provider's authorization flow. We do not sell connected mailbox or calendar data. You can disconnect a provider from the Integrations area, subject to records that must be retained for security or legal purposes.</p><h2>5. Storage and security</h2><p>Credentials and provider tokens are protected using encryption at rest and access controls. No internet transmission or storage method can be guaranteed completely secure, so protect your account credentials and notify us of suspected unauthorized access.</p><h2>6. Retention and deletion</h2><p>We retain information while your account or connected workflows are active and as needed for security, dispute resolution, legal compliance, and operational records. Contact the application administrator to request account or data deletion.</p><h2>7. Contact</h2><p>For privacy questions or requests, contact the administrator associated with your IKRGY workspace.</p></LegalPage> }

function TermsOfService() { return <LegalPage title="Terms of Service"><h2>1. Acceptance</h2><p>By creating an account or using IKRGY Recruiting Automation, you agree to these Terms of Service and applicable law. If you do not agree, do not use the application.</p><h2>2. Account responsibilities</h2><p>You are responsible for providing accurate registration information, protecting your credentials, and all activity performed through your account. Notify your workspace administrator promptly about unauthorized access.</p><h2>3. Connected services</h2><p>You may connect supported Gmail, Google Calendar, and Microsoft Outlook accounts. You authorize the application to use only the permissions required for the features you select. Provider terms and policies also apply.</p><h2>4. Recruiting workflows</h2><p>The application provides operational assistance and recommendations. Recruiters and administrators remain responsible for reviewing outputs, approving actions, complying with employment laws, and making all hiring decisions. The application does not make hiring decisions on your behalf.</p><h2>5. Acceptable use</h2><p>Do not misuse the application, access another user's account, interfere with its operation, upload unlawful material, or use connected services without authorization.</p><h2>6. Availability and changes</h2><p>We may update, suspend, or improve features from time to time. We may update these terms when necessary and will publish the revised version through the application.</p><h2>7. Contact</h2><p>For questions about these terms, contact the administrator associated with your IKRGY workspace.</p></LegalPage> }

function LegalPage({ title, children }: { title: string; children: ReactNode }) { return <main className="legal-page"><header className="legal-header"><Link className="legal-brand" to="/login"><img src={logo} alt="IKRGY logo" /><span>IKRGY Recruiting Automation</span></Link><Link className="secondary" to="/login">Back to sign in</Link></header><article className="legal-content"><span className="eyebrow">IKRGY Recruiting Automation</span><h1>{title}</h1><p className="legal-updated">Effective date: September 17, 2026</p>{children}</article></main> }

function Protected() { const saved = localStorage.getItem('recruiter-session'); if (!saved) return <Navigate to="/login" replace />; return <Portal session={JSON.parse(saved)} /> }
function Portal({ session }: { session: Session }) { const navigate = useNavigate(); const location = useLocation(); const [data, setData] = useState<OverviewData | null>(null); const [error, setError] = useState(''); useEffect(() => { api<OverviewData>('/portal/overview', session).then(setData).catch(e => setError(e.message)) }, [session]); const logout = () => { localStorage.removeItem('recruiter-session'); navigate('/login') }; const nav = [['/dashboard', 'Overview', '◫'], ['/dashboard/rescheduling', 'Rescheduling', '↻'], ['/dashboard/approvals', 'Approval Queue', '✓'], ['/dashboard/ranking', 'Ranking & Alerts', '★'], ['/dashboard/integrations', 'Integrations', '⛓'], ['/dashboard/audit', 'Audit & Observability', '◎'], ['/dashboard/notifications', 'Notifications', '◉'], ['/dashboard/settings', 'Admin Settings', '⚙']] as const; return <div className="app-shell"><aside className="sidebar"><Link className="brand" to="/dashboard"><img src={logo} alt="IKRGY logo" /><span><b>IKRGY</b>Recruiting Automation</span></Link><div className="env-chip">database mode · live</div><nav>{nav.map(([path, label, icon]) => <Link className={`nav-link ${location.pathname === path ? 'active' : ''}`} to={path} key={path}><i>{icon}</i>{label}</Link>)}</nav><div className="sidebar-foot"><div className="security-note"><b>Recruiter-controlled</b><span>No automatic hiring decisions.</span></div><button className="ghost full" onClick={logout}>Sign out</button></div></aside><main className="main"><header className="topbar"><div><h1>{titleFor(location.pathname)}</h1><p>Live operating view for the recruiting automation platform</p></div><div className="top-actions"><span className="live-dot" /> {data?.user.full_name ?? 'Loading'} <span className="role-pill">{data?.user.role ?? 'user'}</span></div></header><section className="content">{error && <div className="error banner">{error}</div>}<Outlet context={{ session, data, refresh: () => api<OverviewData>('/portal/overview', session).then(setData) }} /></section></main></div> }
function titleFor(path: string) { const value = path.split('/').pop(); return ({ dashboard: 'Recruiting Operations', rescheduling: 'Workflow 1 · Candidate Rescheduling', approvals: 'Approval Queue', ranking: 'Workflow 2 · Candidate Ranking & Recruiter Alert', integrations: 'Integrations', audit: 'Audit & Observability', notifications: 'Notifications', settings: 'Admin Settings' } as Record<string, string>)[value ?? 'dashboard'] }
function OverviewPage() { const { data } = useOutletData(); if (!data) return <Loading />; return <><section className="hero-strip"><div><span className="eyebrow">Shared platform spine</span><h2>Two workflows. One controlled recruiting platform.</h2><p>Live data from your account and connected communication systems.</p></div><div className="hero-actions"><Link className="primary" to="/dashboard/rescheduling">Open rescheduling</Link><Link className="secondary" to="/dashboard/ranking">Open ranking</Link></div></section><div className="kpi-grid"><Kpi label="Synced emails" value={data.metrics.email_count} tone="cyan" /><Kpi label="Reschedule requests" value={data.metrics.reschedule_count} tone="violet" /><Kpi label="Google connected" value={data.google_connected ? 'Yes' : 'No'} tone="orange" /><Kpi label="Integrations" value="Manage" tone="green" /></div><div className="grid-2"><Panel title="Workflow health" subtitle="Runtime stages and control gates"><div className="workflow"><Workflow label="Inbox → calendar → approval → reply" /><Workflow label="Recruiter review remains final" alt /></div></Panel><Panel title="Connected systems" subtitle="Manage communication providers"><div className="list"><div className="list-row"><span className={`status-dot ${data.google_connected ? 'running' : 'offline'}`} /><div><b>Google Workspace</b><small>{data.google_connected ? 'Gmail and Calendar connected' : 'Connect Gmail and Calendar in Integrations'}</small></div><Link className="badge" to="/dashboard/integrations">Manage</Link></div><div className="list-row"><span className="status-dot offline" /><div><b>Microsoft Outlook</b><small>Connect from Integrations when configured</small></div><Link className="badge" to="/dashboard/integrations">Manage</Link></div></div></Panel></div></> }
function ReschedulingPage() { const { session } = useOutletData(); const [messages, setMessages] = useState<Message[]>([]); const [gmail, setGmail] = useState<GmailStatus | null>(null); const [status, setStatus] = useState(''); const [syncing, setSyncing] = useState(false); const load = async () => { try { const [statusData, messageData] = await Promise.all([api<GmailStatus>('/integrations/google/gmail/status', session), api<Message[]>('/integrations/google/gmail/messages', session)]); setGmail(statusData); setMessages(messageData); setStatus('') } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to load Gmail') } }; useEffect(() => { load() }, [session]); const sync = async () => { setSyncing(true); setStatus(''); try { const result = await api<GmailSyncResponse>('/integrations/google/gmail/sync?max_results=50', session, { method: 'POST' }); await load(); setStatus(`Gmail sync complete: ${result.new} new message${result.new === 1 ? '' : 's'} imported.`) } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to sync Gmail') } finally { setSyncing(false) } }; return <><PageIntro kicker="Workflow 1 · Step 1" title="Connect inbox signals." copy="Import recent Gmail inbox messages into the recruiting workspace. Nothing is sent or changed by this step." /><div className="sync-toolbar"><div><span className={`status-dot ${gmail?.connected ? 'running' : 'offline'}`} /><strong>{gmail?.connected ? `Connected${gmail.email ? ` · ${gmail.email}` : ''}` : 'Google account not connected'}</strong><small>{gmail?.message_count ?? 0} messages stored in this workspace</small></div><div className="sync-actions"><Link className="secondary" to="/dashboard/integrations">Manage connection</Link><button className="primary" onClick={sync} disabled={!gmail?.connected || syncing}>{syncing ? 'Syncing…' : 'Sync Gmail'}</button></div></div>{status && <div className="sync-result">{status}</div>}<Panel title="Inbox signals" subtitle="Messages imported from the connected Gmail inbox"><div className="table-wrap"><table><thead><tr><th>Sender</th><th>Subject</th><th>Received</th><th>Classification</th></tr></thead><tbody>{messages.map(message => <tr key={message.id}><td>{message.sender}</td><td><strong>{message.subject || '(No subject)'}</strong><small>{message.body_preview?.slice(0, 110) || 'No preview available'}</small></td><td>{message.received_at ? new Date(message.received_at).toLocaleString() : '—'}</td><td><span className="badge">{message.classification}</span></td></tr>)}</tbody></table>{!messages.length && <Empty text={status || (gmail?.connected ? 'No Gmail messages imported yet. Select Sync Gmail to begin.' : 'Connect Google from Integrations before syncing Gmail.')} />}</div></Panel></> }
function ApprovalsPage() { return <><PageIntro kicker="Human-in-the-loop" title="Approval queue." copy="Only backend-created workflow proposals appear here. No sample approvals are shown." /><Panel title="Pending review" subtitle="Live automation records"><Empty text="No pending approvals in the database." /></Panel></> }
function RankingPage() { return <><PageIntro kicker="Workflow 2" title="Ranking and recruiter alerts." copy="Candidate rankings will appear here once requisition and applicant APIs are connected." /><Panel title="Active requisitions" subtitle="Database-backed records only"><Empty text="No requisitions available from the backend yet." /></Panel></> }
function IntegrationsPage() { const { session, data } = useOutletData(); const [outlookConnected, setOutlookConnected] = useState(false); const [status, setStatus] = useState(''); useEffect(() => { api<{ connected: boolean }>('/integrations/outlook/status', session).then(result => setOutlookConnected(result.connected)).catch(() => undefined) }, [session]); const connectGoogle = async () => { const result = await api<{ authorization_url: string }>('/integrations/google/authorize', session); window.location.href = result.authorization_url }; const connectOutlook = async () => { try { const result = await api<{ authorization_url: string }>('/integrations/outlook/authorize', session); window.location.href = result.authorization_url } catch (e) { setStatus(e instanceof Error ? e.message : 'Unable to connect Outlook') } }; return <><PageIntro kicker="Connected systems" title="Integrations." copy="Connect Gmail, Google Calendar, and Microsoft Outlook directly from your application workspace." />{status && <div className="error banner">{status}</div>}<div className="integration-grid"><Integration name="Gmail" status={data?.google_connected ? 'connected' : 'not connected'} action={connectGoogle} /><Integration name="Google Calendar" status={data?.google_connected ? 'connected' : 'not connected'} action={connectGoogle} /><Integration name="Microsoft Outlook" status={outlookConnected ? 'connected' : 'not connected'} action={connectOutlook} /></div></> }
function AuditPage() { return <><PageIntro kicker="Observability" title="Audit trail." copy="Every workflow action will be rendered from backend audit records as that API is added." /><Panel title="Append-only event trail" subtitle="Trigger, decisions, guardrails, approvals, actions"><Empty text="No audit events available from the backend." /></Panel></> }
function NotificationsPage() { return <><PageIntro kicker="Operations" title="Notifications." copy="Recruiter-facing updates will appear here from backend workflow events." /><Panel title="All channels" subtitle="Email · Dashboard"><Empty text="No notifications available." /></Panel></> }
function SettingsPage() { const { data } = useOutletData(); return <><PageIntro kicker="Configuration" title="Admin settings." copy="Settings are shown from live backend state. Policy mutations remain backend-controlled." /><Panel title="Workspace access" subtitle="Current authenticated account"><div className="settings"><div><span>Role</span><b>{data?.user.role ?? '—'}</b></div><div><span>Company</span><b>{data?.user.company_id ?? '—'}</b></div><div><span>Google connection</span><b>{data?.google_connected ? 'Connected' : 'Not connected'}</b></div></div></Panel></> }
function PageIntro({ kicker, title, copy }: { kicker: string; title: string; copy: string }) { return <div className="page-intro"><span className="eyebrow">{kicker}</span><h2>{title}</h2><p>{copy}</p></div> }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="card"><div className="card-head"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</section> }
function Kpi({ label, value, tone }: { label: string; value: string | number; tone: string }) { return <div className={`kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>From live database</small></div> }
function Workflow({ label, alt = false }: { label: string; alt?: boolean }) { return <div className="workflow-row"><span className={`workflow-mark ${alt ? 'alt' : ''}`}>✓</span><div><b>{label}</b><small>{alt ? 'Human decision boundary' : 'Backend automation path'}</small></div></div> }
function Integration({ name, status, action }: { name: string; status: string; action: () => void }) { return <section className="integration-card"><div className="integration-title"><span className="integration-logo">{name[0]}</span><div><h3>{name}</h3><p>OAuth 2.0 API</p></div></div><span className="badge">{status}</span><button className="secondary" onClick={action}>{status === 'connected' ? 'Reconnect' : 'Connect Google'}</button></section> }
function Empty({ text }: { text: string }) { return <div className="empty"><span>◌</span>{text}</div> }
function Loading() { return <div className="loading">Loading live data…</div> }
function useOutletData() { const saved = localStorage.getItem('recruiter-session'); const session = (saved ? JSON.parse(saved) : null) as Session; const [data, setData] = useState<OverviewData | null>(null); useEffect(() => { if (session) api<OverviewData>('/portal/overview', session).then(setData).catch(() => setData(null)) }, [session]); return { session, data } }
export default App
